const photo = require('../../services/photo');
const { choosePhotos, uploadPhoto } = require('../../services/file');
const ui = require('../../utils/photo-ui');
const { getActivityDetail } = require('../../services/activity');

Page({
  data: { activityId: '', activityStatus: '', canUploadPhoto: true, loading: true, loadingMore: false, error: '', summary: null, items: [], page: 1, hasMore: true, scope: 'ALL', sort: 'LATEST', layout: 3, toolVisible: false, draftScope: 'ALL', draftSort: 'LATEST', draftLayout: 3, previewVisible: false, previewPhoto: null, uploadTasks: [], uploadVisible: false },
  onLoad(options) { const preferences = ui.loadPreferences(); this.initialPhotoId = options.photoId || ''; this.setData({ activityId: options.activityId || '', ...preferences, draftScope: preferences.scope, draftSort: preferences.sort, draftLayout: preferences.layout }); },
  onShow() { if (this.data.activityId) this.refresh(); },
  onHide() { this.stopPolling(); }, onUnload() { this.stopPolling(); },
  async refresh() { if (this.refreshing) return; this.refreshing = true; this.setData({ loading: true, error: '', page: 1, hasMore: true }); try { const [activity] = await Promise.all([getActivityDetail(this.data.activityId), this.loadSummary(), this.loadPage(1, true)]); this.setData({ activityStatus: activity.status, canUploadPhoto: activity.status !== 'CANCELED' }); } catch (error) { this.setData({ error: error.message || '照片加载失败' }); } finally { this.refreshing = false; this.setData({ loading: false }); wx.stopPullDownRefresh(); } },
  onPullDownRefresh() { this.refresh(); },
  async loadSummary() { const summary = await photo.getPhotoSummary(this.data.activityId); this.setData({ summary }); this.updatePolling(); return summary; },
  async loadPage(page, replace) { const response = await photo.getPhotos(this.data.activityId, { scope: this.data.scope, sort: this.data.sort, page, pageSize: 30 }); const items = replace ? (response.items || []) : ui.appendPage(this.data.items, response); const normalized = items.map(item => ({ ...item, avatarText: (item.uploaderNickname || '玩').slice(0, 1), statusMeta: ui.photoStatus(item.auditStatus, item.visibilityStatus), timeText: ui.formatPhotoTime(item.createTime) })); this.setData({ items: normalized, page: Number(response.page || page), hasMore: normalized.length < Number(response.total || 0) }); if (this.initialPhotoId) { const target = normalized.find(item => String(item.photoId) === String(this.initialPhotoId)); if (target) { this.setData({ previewPhoto: target, previewVisible: true }); this.initialPhotoId = ''; } } this.updatePolling(); },
  async onReachBottom() { if (this.data.loading || this.data.loadingMore || !this.data.hasMore) return; this.setData({ loadingMore: true }); try { await this.loadPage(this.data.page + 1, false); } catch (error) { wx.showToast({ title: error.message || '加载失败，点击重试', icon: 'none' }); this.setData({ error: '加载更多失败，点击重试' }); } finally { this.setData({ loadingMore: false }); } },
  retry() { this.refresh(); },
  openTools() { this.setData({ toolVisible: true, draftScope: this.data.scope, draftSort: this.data.sort, draftLayout: this.data.layout }); }, closeTools() { this.setData({ toolVisible: false }); },
  pickScope(e) { this.setData({ draftScope: e.currentTarget.dataset.value }); }, pickSort(e) { this.setData({ draftSort: e.currentTarget.dataset.value }); }, pickLayout(e) { this.setData({ draftLayout: Number(e.currentTarget.dataset.value) }); },
  resetTools() { this.setData({ draftScope: 'ALL', draftSort: 'LATEST', draftLayout: 3 }); },
  applyTools() { const next = ui.savePreferences({ scope: this.data.draftScope, sort: this.data.draftSort, layout: this.data.draftLayout }); this.setData({ ...next, toolVisible: false }); this.refresh(); },
  openPreview(e) { const current = this.data.items.find(item => String(item.photoId) === String(e.currentTarget.dataset.id)); if (current) this.setData({ previewPhoto: current, previewVisible: true }); }, closePreview() { this.setData({ previewVisible: false, previewPhoto: null }); }, stopPreviewClose() {},
  async toggleLike() { const before = this.data.previewPhoto; if (!before) return; const desired = !before.likedByMe; const next = ui.optimisticLike(before, desired); this.applyPhotoPatch(before.photoId, next); try { desired ? await photo.likePhoto(this.data.activityId, before.photoId) : await photo.unlikePhoto(this.data.activityId, before.photoId); } catch (error) { this.applyPhotoPatch(before.photoId, before); wx.showToast({ title: error.message || '操作失败', icon: 'none' }); } },
  applyPhotoPatch(photoId, patch) { const current = this.data.previewPhoto; this.setData({ items: ui.patchPhoto(this.data.items, photoId, patch), previewPhoto: current && String(current.photoId) === String(photoId) ? { ...current, ...patch } : current }); },
  goDetail() { const item = this.data.previewPhoto; if (item) wx.navigateTo({ url: `/pages/photo-detail/index?activityId=${this.data.activityId}&photoId=${item.photoId}` }); },
  confirmDelete() { const item = this.data.previewPhoto; if (!item || !item.canDelete) return; wx.showModal({ title: '删除这张照片？', content: '删除后将从活动照片墙中移除，此操作无法撤销。', confirmColor: '#D94C4C', success: async result => { if (!result.confirm) return; try { await photo.deletePhoto(this.data.activityId, item.photoId); this.setData({ items: this.data.items.filter(row => String(row.photoId) !== String(item.photoId)) }); this.closePreview(); await this.loadSummary(); wx.showToast({ title: '已删除', icon: 'success' }); } catch (error) { wx.showToast({ title: error.message || '删除失败', icon: 'none' }); } } }); },
  async chooseAndUpload() { try { const paths = await choosePhotos(); const tasks = paths.map((path, index) => ({ id: `${Date.now()}-${index}`, path, status: 'WAITING', statusText: '等待上传' })); this.setData({ uploadTasks: tasks, uploadVisible: true }); await this.uploadBatch(tasks); } catch (error) { if (error.code !== 'CHOOSE_IMAGE_ERROR') wx.showToast({ title: error.message || '选择照片失败', icon: 'none' }); } },
  async uploadBatch(tasks) { const finished = []; let failed = false; for (const task of tasks) { this.updateTask(task.id, { status: 'UPLOADING', statusText: '上传中' }); try { const result = await uploadPhoto(task.path); finished.push(result.fileId); this.updateTask(task.id, { status: 'UPLOADED', statusText: '等待绑定', fileId: result.fileId }); } catch (error) { failed = true; this.updateTask(task.id, { status: 'FAILED', statusText: error.message || '上传失败' }); } }
    if (failed) { wx.showToast({ title: `${finished.length} / ${tasks.length} 上传成功，请重新选择失败照片`, icon: 'none' }); return; }
    try { const created = await photo.createPhotos(this.data.activityId, finished); (created || []).forEach((item, index) => this.updateTask(tasks[index].id, { status: 'PENDING', statusText: '审核中', photoId: item.photoId })); wx.showToast({ title: '已提交审核', icon: 'success' }); await this.refresh(); } catch (error) { tasks.forEach(task => this.updateTask(task.id, { status: 'FAILED', statusText: '绑定失败，稍后可重新上传' })); wx.showToast({ title: error.message || '绑定照片失败', icon: 'none' }); }
  },
  updateTask(id, patch) { this.setData({ uploadTasks: (this.data.uploadTasks || []).map(item => item.id === id ? { ...item, ...patch } : item) }); }, closeUpload() { this.setData({ uploadVisible: false }); },
  updatePolling() { const needsPolling = (this.data.summary && Number(this.data.summary.pendingAuditCount || 0) > 0) || this.data.items.some(item => ['PENDING', 'REVIEWING'].includes(item.auditStatus) || item.visibilityStatus === 'REVIEWING'); if (needsPolling && !this.pollTimer) this.pollTimer = setInterval(() => this.refresh(), 8000); if (!needsPolling) this.stopPolling(); }, stopPolling() { if (this.pollTimer) { clearInterval(this.pollTimer); this.pollTimer = null; } }
});
