package com.playmate.space.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.LocalDateTime;

@TableName("t_activity_todo")
public class ActivityTodoEntity {
    @TableId(type = IdType.AUTO) private Long id;
    private Long activityId; private String todoType; private String sourceType; private Long sourceId; private String sourceKey;
    private String title; private String content; private String actionType; private LocalDateTime dueTime; private String status;
    private Integer autoGenerated; private Long createdBy; private Integer version; private LocalDateTime createTime; private LocalDateTime updateTime;
    @TableLogic(value = "0", delval = "1") private Integer deleteFlag;
    public Long getId(){return id;} public void setId(Long v){id=v;} public Long getActivityId(){return activityId;} public void setActivityId(Long v){activityId=v;}
    public String getTodoType(){return todoType;} public void setTodoType(String v){todoType=v;} public String getSourceType(){return sourceType;} public void setSourceType(String v){sourceType=v;}
    public Long getSourceId(){return sourceId;} public void setSourceId(Long v){sourceId=v;} public String getSourceKey(){return sourceKey;} public void setSourceKey(String v){sourceKey=v;}
    public String getTitle(){return title;} public void setTitle(String v){title=v;} public String getContent(){return content;} public void setContent(String v){content=v;}
    public String getActionType(){return actionType;} public void setActionType(String v){actionType=v;} public LocalDateTime getDueTime(){return dueTime;} public void setDueTime(LocalDateTime v){dueTime=v;}
    public String getStatus(){return status;} public void setStatus(String v){status=v;} public Integer getAutoGenerated(){return autoGenerated;} public void setAutoGenerated(Integer v){autoGenerated=v;}
    public Long getCreatedBy(){return createdBy;} public void setCreatedBy(Long v){createdBy=v;} public Integer getVersion(){return version;} public void setVersion(Integer v){version=v;}
    public LocalDateTime getCreateTime(){return createTime;} public void setCreateTime(LocalDateTime v){createTime=v;} public LocalDateTime getUpdateTime(){return updateTime;} public void setUpdateTime(LocalDateTime v){updateTime=v;}
    public Integer getDeleteFlag(){return deleteFlag;} public void setDeleteFlag(Integer v){deleteFlag=v;}
}
