const photo = require('../../services/photo');
const ui = require('../../utils/photo-ui');
const REPORT_REASONS = [{ code: 'SEXUAL', label: '色情 / 低俗' }, { code: 'VIOLENCE', label: '暴力 / 血腥' }, { code: 'ILLEGAL', label: '违法违规' }, { code: 'PRIVACY', label: '隐私 / 不适合在本活动展示' }, { code: 'OTHER', label: '其他' }];

Page({
  data: { activityId: '', photoId: '', loading: true, error: '', photo: null, moreVisible: false, reportVisible: false, reasons: REPORT_REASONS },
  onLoad(options) { this.setData({ activityId: options.activityId || '', photoId: options.photoId || '' }); },
  onShow() { if (this.data.activityId && this.data.photoId) this.load(); },
  async load() { this.setData({ loading: true, error: '' }); try { const item = await photo.getPhotoDetail(this.data.activityId, this.data.photoId); this.setData({ photo: this.mapPhoto(item) }); } catch (error) { this.setData({ error: error.message || '照片详情加载失败' }); } finally { this.setData({ loading: false }); } },
  mapPhoto(item) { const statusMeta = ui.photoStatus(item.auditStatus, item.visibilityStatus); const descriptions = { pending: '审核完成前，仅你自己可以看到这张照片。', rejected: '该照片未通过内容安全审核，不会在活动照片墙中展示。', reviewing: '该照片正在重新审核，暂时不会对其他成员展示。' }; return { ...item, avatarText: (item.uploaderNickname || '玩').slice(0, 1), statusMeta, canLike: ui.isLikable(item), statusDescription: descriptions[statusMeta.className] || '', uploadTimeText: ui.formatPhotoTime(item.uploadTime), sizeText: ui.formatFileSize(item.size), dimensionsText: ui.formatDimensions(item.width, item.height) }; },
  async toggleLike() { const before = this.data.photo; if (!before || !before.canLike) return; const desired = !before.likedByMe; this.setData({ photo: ui.optimisticLike(before, desired) }); try { desired ? await photo.likePhoto(this.data.activityId, before.photoId) : await photo.unlikePhoto(this.data.activityId, before.photoId); } catch (error) { this.setData({ photo: before }); wx.showToast({ title: error.message || '操作失败', icon: 'none' }); } },
  async viewOriginal() { try { const result = await photo.getOriginalUrl(this.data.activityId, this.data.photoId); if (!result || !result.url) throw new Error('原图地址获取失败'); wx.previewImage({ current: result.url, urls: [result.url] }); } catch (error) { wx.showToast({ title: error.message || '原图加载失败', icon: 'none' }); } },
  openMore() { this.setData({ moreVisible: true }); }, closeMore() { this.setData({ moreVisible: false }); }, openReport() { if (this.data.photo && this.data.photo.canReport) this.setData({ moreVisible: false, reportVisible: true }); }, closeReport() { this.setData({ reportVisible: false }); }, stop() {},
  async submitReport(e) { const reason = e.currentTarget.dataset.reason; try { await photo.reportPhoto(this.data.activityId, this.data.photoId, reason); this.closeReport(); wx.showToast({ title: '已提交举报，照片将进入复核', icon: 'none' }); setTimeout(() => wx.navigateBack(), 450); } catch (error) { wx.showToast({ title: error.message || '举报失败', icon: 'none' }); } },
  confirmDelete() { const item = this.data.photo; if (!item || !item.canDelete) return; this.closeMore(); wx.showModal({ title: '删除这张照片？', content: '删除后将从活动照片墙中移除，此操作无法撤销。', confirmColor: '#D94C4C', success: async result => { if (!result.confirm) return; try { await photo.deletePhoto(this.data.activityId, item.photoId); wx.showToast({ title: '已删除', icon: 'success' }); setTimeout(() => wx.navigateBack(), 500); } catch (error) { wx.showToast({ title: error.message || '删除失败', icon: 'none' }); } } }); }
});
