package com.playmate.space.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.playmate.space.common.ErrorCode;
import com.playmate.space.common.exception.BusinessException;
import com.playmate.space.common.exception.ForbiddenException;
import com.playmate.space.common.exception.NotFoundException;
import com.playmate.space.dto.poll.*;
import com.playmate.space.entity.*;
import com.playmate.space.mapper.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.time.*;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class PollService {
    private static final Logger log = LoggerFactory.getLogger(PollService.class);
    private static final Set<String> PURPOSES = Set.of("GENERAL","UPDATE_ITINERARY","CREATE_ITINERARY");
    private static final Set<String> DECISIONS = Set.of("PLACE","TIME","TRANSPORT","CONTENT","RESTAURANT","OTHER");
    private static final Set<String> VOTE_TYPES = Set.of("SINGLE","MULTIPLE");
    private final ActivityCollaborationAccess access; private final ActivityPollMapper pollMapper; private final ActivityPollOptionMapper optionMapper; private final ActivityPollVoteMapper voteMapper; private final ActivityItineraryMapper itineraryMapper; private final ObjectMapper objectMapper;
    public PollService(ActivityCollaborationAccess access, ActivityPollMapper pollMapper, ActivityPollOptionMapper optionMapper, ActivityPollVoteMapper voteMapper, ActivityItineraryMapper itineraryMapper, ObjectMapper objectMapper) { this.access=access;this.pollMapper=pollMapper;this.optionMapper=optionMapper;this.voteMapper=voteMapper;this.itineraryMapper=itineraryMapper;this.objectMapper=objectMapper; }

    public List<PollListItemResponse> list(Long activityId) { Long userId=access.requireUserId(); access.requireActivity(activityId); access.requireActiveMember(activityId,userId); finalizeExpiredByActivity(activityId); return listInternal(activityId,userId); }
    public PollDetailResponse detail(Long activityId,Long pollId){Long userId=access.requireUserId();access.requireActivity(activityId);access.requireActiveMember(activityId,userId);finalizeExpiredPollIfNeeded(pollId);return detailInternal(activityId,pollId,userId);}

    @Transactional public PollDetailResponse create(Long activityId,CreatePollRequest request){ Long userId=access.requireUserId();ActivityEntity a=access.requireActivity(activityId);access.requireActiveMember(activityId,userId);access.requireWritableActivity(a);ActivityPollEntity poll=createInternal(a,userId,request,null,null);return detailInternal(activityId,poll.getId(),userId); }
    public void createLinkedItineraryPoll(ActivityEntity activity, ActivityItineraryEntity itinerary, Long userId, CreatePollRequest request){ createInternal(activity,userId,request,itinerary.getId(),itinerary.getVersion()); }

    @Transactional public PollDetailResponse update(Long activityId,Long pollId,UpdatePollRequest request){Long userId=access.requireUserId();ActivityEntity a=access.requireActivity(activityId);ActivityMemberEntity m=access.requireActiveMember(activityId,userId);access.requireWritableActivity(a);ActivityPollEntity p=requirePoll(activityId,pollId);requirePollManager(a,m,userId,p);if(!"DRAFT".equals(p.getStatus())&&!"ACTIVE".equals(p.getStatus()))throw param("当前投票不能编辑");if(request.title()!=null){if(!StringUtils.hasText(request.title()))throw param("投票标题不能为空");p.setTitle(request.title().trim());}if(request.description()!=null)p.setDescription(trim(request.description()));if(request.deadline()!=null)p.setDeadline(request.deadline());if(request.allowModify()!=null)p.setAllowModify(request.allowModify()?1:0);p.setVersion(p.getVersion()+1);p.setUpdateTime(LocalDateTime.now());pollMapper.updateById(p);return detailInternal(activityId,pollId,userId);}

    @Transactional public PollDetailResponse submitVote(Long activityId,Long pollId,VoteRequest request){Long userId=access.requireUserId();ActivityEntity a=access.requireActivity(activityId);access.requireActiveMember(activityId,userId);access.requireWritableActivity(a);finalizeExpiredPollIfNeeded(pollId);ActivityPollEntity p=requirePoll(activityId,pollId);if(!"ACTIVE".equals(p.getStatus()))throw param("投票已结束，不能继续参与");Set<Long> selected=new LinkedHashSet<>(request.optionIds());if(selected.size()!=request.optionIds().size())throw param("投票选项不能重复");if("SINGLE".equals(p.getVoteType())&&selected.size()!=1)throw param("单选投票只能选择一个选项");Set<Long> valid=optionMapper.selectList(new LambdaQueryWrapper<ActivityPollOptionEntity>().eq(ActivityPollOptionEntity::getPollId,pollId)).stream().map(ActivityPollOptionEntity::getId).collect(Collectors.toSet());if(!valid.containsAll(selected))throw param("包含无效投票选项");
        LocalDateTime now=LocalDateTime.now();List<ActivityPollVoteEntity> existing=voteMapper.selectList(new LambdaQueryWrapper<ActivityPollVoteEntity>().eq(ActivityPollVoteEntity::getPollId,pollId).eq(ActivityPollVoteEntity::getUserId,userId));Set<Long> old=existing.stream().map(ActivityPollVoteEntity::getOptionId).collect(Collectors.toSet());
        if ("SINGLE".equals(p.getVoteType())) {
            // Repair historical inconsistent data in the same transaction before writing the new choice.
            voteMapper.removeOtherActiveVotes(pollId, userId, selected.iterator().next(), now);
        }
        for(ActivityPollVoteEntity vote:existing)if(!selected.contains(vote.getOptionId())){vote.setDeleteFlag(1);vote.setUpdateTime(now);voteMapper.updateById(vote);}for(Long optionId:selected)if(!old.contains(optionId)){int restored=voteMapper.restoreVote(pollId,optionId,userId,now);if(restored==0){ActivityPollVoteEntity vote=new ActivityPollVoteEntity();vote.setPollId(pollId);vote.setOptionId(optionId);vote.setUserId(userId);vote.setCreateTime(now);vote.setUpdateTime(now);vote.setDeleteFlag(0);voteMapper.insert(vote);}}
        return detailInternal(activityId,pollId,userId);}

    @Transactional public PollDetailResponse close(Long activityId,Long pollId){Long userId=access.requireUserId();ActivityEntity a=access.requireActivity(activityId);ActivityMemberEntity m=access.requireActiveMember(activityId,userId);access.requireWritableActivity(a);ActivityPollEntity p=requirePoll(activityId,pollId);requirePollManager(a,m,userId,p);closeAndFinalize(p,a);return detailInternal(activityId,pollId,userId);}
    @Transactional public PollDetailResponse cancel(Long activityId,Long pollId){Long userId=access.requireUserId();ActivityEntity a=access.requireActivity(activityId);ActivityMemberEntity m=access.requireActiveMember(activityId,userId);access.requireWritableActivity(a);ActivityPollEntity p=requirePoll(activityId,pollId);requirePollManager(a,m,userId,p);if(!"DRAFT".equals(p.getStatus())&&!"ACTIVE".equals(p.getStatus()))throw param("当前投票不能取消");p.setStatus("CANCELED");p.setUpdateTime(LocalDateTime.now());p.setVersion(p.getVersion()+1);pollMapper.updateById(p);return detailInternal(activityId,pollId,userId);}
    @Transactional public PollDetailResponse applyResult(Long activityId,Long pollId,ApplyPollResultRequest request){Long userId=access.requireUserId();ActivityEntity a=access.requireActivity(activityId);ActivityMemberEntity m=access.requireActiveMember(activityId,userId);access.requireWritableActivity(a);ActivityPollEntity p=requirePoll(activityId,pollId);if(!"CLOSED".equals(p.getStatus()))throw param("投票尚未结束");if("GENERAL".equals(p.getPurpose()))throw param("普通投票不需要应用结果");ActivityPollOptionEntity option=requireOption(pollId,request.optionId());if("UPDATE_ITINERARY".equals(p.getPurpose())){ActivityItineraryEntity target=requireTarget(p);if(!userId.equals(target.getCreatedBy())&&!access.isActivityCreator(a,m,userId))throw new ForbiddenException("只有行程创建者或活动创建者可以确认应用结果");}else if(!userId.equals(p.getCreatedBy())&&!access.isActivityCreator(a,m,userId))throw new ForbiddenException("无权确认投票结果");p.setWinnerOptionId(option.getId());applyResultInternal(p,a,option,true);return detailInternal(activityId,pollId,userId);}

    public List<PollListItemResponse> listForItineraryInternal(Long activityId,Long itineraryId,Long userId){finalizeExpiredByActivity(activityId);return listInternal(activityId,userId).stream().filter(p->itineraryId.equals(p.targetItineraryId())||itineraryId.equals(p.generatedItineraryId())).toList();}
    public void finalizeExpiredPollIfNeeded(Long pollId){ActivityPollEntity p=pollMapper.selectById(pollId);if(p==null||!"ACTIVE".equals(p.getStatus())||p.getDeadline()==null||p.getDeadline().isAfter(LocalDateTime.now()))return;ActivityEntity a=access.requireActivity(p.getActivityId());closeAndFinalize(p,a);}
    private void finalizeExpiredByActivity(Long activityId){List<ActivityPollEntity> polls=pollMapper.selectList(new LambdaQueryWrapper<ActivityPollEntity>().eq(ActivityPollEntity::getActivityId,activityId).eq(ActivityPollEntity::getStatus,"ACTIVE").le(ActivityPollEntity::getDeadline,LocalDateTime.now()));for(ActivityPollEntity p:polls)finalizeExpiredPollIfNeeded(p.getId());}

    private ActivityPollEntity createInternal(ActivityEntity a,Long userId,CreatePollRequest r,Long forcedTargetId,Integer forcedVersion){String purpose=upper(r.purpose());String voteType=upper(r.voteType());String decision=upper(r.decisionType());if(!PURPOSES.contains(purpose)||!VOTE_TYPES.contains(voteType)||!DECISIONS.contains(decision))throw param("投票参数不合法");if(("UPDATE_ITINERARY".equals(purpose)||"CREATE_ITINERARY".equals(purpose))&&!"SINGLE".equals(voteType))throw param("关联行程的投票必须使用单选");Long targetId=forcedTargetId!=null?forcedTargetId:r.targetItineraryId();Integer targetVersion=forcedVersion;if("UPDATE_ITINERARY".equals(purpose)){if(targetId==null)throw param("关联已有行程时必须指定目标行程");ActivityItineraryEntity target=itineraryMapper.selectById(targetId);if(target==null||!a.getId().equals(target.getActivityId()))throw param("关联行程不存在");if(targetVersion==null)targetVersion=target.getVersion();}if("CREATE_ITINERARY".equals(purpose)&&(r.itineraryTemplate()==null||r.itineraryTemplate().isEmpty()))throw param("生成行程投票需要固定行程信息");
        LocalDateTime now=LocalDateTime.now();ActivityPollEntity p=new ActivityPollEntity();p.setActivityId(a.getId());p.setPurpose(purpose);p.setDecisionType(decision);p.setTargetItineraryId(targetId);p.setTitle(r.title().trim());p.setDescription(trim(r.description()));p.setVoteType(voteType);p.setAllowModify(Boolean.TRUE.equals(r.allowModify())?1:0);p.setDeadline(r.deadline());p.setStatus("ACTIVE");p.setResultApplyMode("GENERAL".equals(purpose)?"NONE":"AUTO");p.setResultApplyStatus("GENERAL".equals(purpose)?"NOT_REQUIRED":"PENDING");p.setTargetItineraryVersion(targetVersion);p.setItineraryTemplate(json(r.itineraryTemplate()));p.setCreatedBy(userId);p.setVersion(0);p.setCreateTime(now);p.setUpdateTime(now);p.setDeleteFlag(0);pollMapper.insert(p);int sort=0;for(PollOptionRequest o:r.options()){ActivityPollOptionEntity option=new ActivityPollOptionEntity();option.setPollId(p.getId());option.setOptionText(o.optionText().trim());option.setOptionDescription(trim(o.optionDescription()));option.setResultPayload(json(o.resultPayload()));option.setSortNo(sort++);option.setCreateTime(now);option.setUpdateTime(now);option.setDeleteFlag(0);optionMapper.insert(option);}return p;}
    private void closeAndFinalize(ActivityPollEntity p,ActivityEntity a){if(!"ACTIVE".equals(p.getStatus()))return;LocalDateTime now=LocalDateTime.now();if(pollMapper.closeActivePoll(p.getId(),now)!=1)return;ActivityPollEntity closed=pollMapper.selectById(p.getId());List<ActivityPollVoteEntity> votes=voteMapper.selectList(new LambdaQueryWrapper<ActivityPollVoteEntity>().eq(ActivityPollVoteEntity::getPollId,p.getId()));Map<Long,Long> counts=votes.stream().collect(Collectors.groupingBy(ActivityPollVoteEntity::getOptionId,Collectors.counting()));if("GENERAL".equals(closed.getPurpose())){closed.setResultApplyStatus("NOT_REQUIRED");closed.setUpdateTime(now);pollMapper.updateById(closed);return;}if(counts.isEmpty()){review(closed);return;}long max=counts.values().stream().max(Long::compareTo).orElse(0L);List<Long>winners=counts.entrySet().stream().filter(e->e.getValue()==max).map(Map.Entry::getKey).toList();if(winners.size()!=1){review(closed);return;}ActivityPollOptionEntity winner=requireOption(closed.getId(),winners.getFirst());closed.setWinnerOptionId(winner.getId());applyResultInternal(closed,a,winner,false);}
    private void applyResultInternal(ActivityPollEntity p,ActivityEntity a,ActivityPollOptionEntity winner,boolean manual){try{if("UPDATE_ITINERARY".equals(p.getPurpose()))applyUpdate(p,a,winner,manual);else if("CREATE_ITINERARY".equals(p.getPurpose()))applyCreate(p,a,winner,manual);else {p.setResultApplyStatus("NOT_REQUIRED");pollMapper.updateById(p);}}catch(BusinessException ex){if(manual)throw ex;review(p);}}
    private void applyUpdate(ActivityPollEntity p,ActivityEntity a,ActivityPollOptionEntity winner,boolean manual){ActivityItineraryEntity target=requireTarget(p);if(!manual&&!p.getCreatedBy().equals(target.getCreatedBy())&&!p.getCreatedBy().equals(a.getCreatorUserId())){review(p);return;}if(!Objects.equals(target.getVersion(),p.getTargetItineraryVersion())){review(p);return;}Map<String,Object> payload=map(winner.getResultPayload());if(payload.isEmpty()){review(p);return;}applyPayload(target,payload);target.setPlanningStatus("CONFIRMED");target.setVersion(target.getVersion()+1);target.setUpdateTime(LocalDateTime.now());itineraryMapper.updateById(target);markApplied(p);}
    private void applyCreate(ActivityPollEntity p,ActivityEntity a,ActivityPollOptionEntity winner,boolean manual){Map<String,Object> merged=new LinkedHashMap<>(map(p.getItineraryTemplate()));merged.putAll(map(winner.getResultPayload()));String title=str(merged,"title");String date=str(merged,"itineraryDate");if(!StringUtils.hasText(title)||!StringUtils.hasText(date)){review(p);return;}ActivityItineraryEntity i=new ActivityItineraryEntity();i.setActivityId(a.getId());i.setTitle(title);i.setItineraryType(upperOr(str(merged,"itineraryType"),"OTHER"));i.setItineraryDate(LocalDate.parse(date));i.setAllDay(bool(merged,"allDay")?1:0);i.setStartTime(bool(merged,"allDay")?null:time(merged,"startTime"));i.setEndTime(bool(merged,"allDay")?null:time(merged,"endTime"));i.setLocationName(str(merged,"locationName"));i.setAddress(str(merged,"address"));i.setDescription(str(merged,"description"));i.setPlanningStatus("CONFIRMED");i.setOriginType("POLL_RESULT");i.setOriginPollId(p.getId());i.setCreatedBy(p.getCreatedBy());i.setVersion(0);i.setCreateTime(LocalDateTime.now());i.setUpdateTime(LocalDateTime.now());i.setDeleteFlag(0);itineraryMapper.insert(i);p.setGeneratedItineraryId(i.getId());markApplied(p);}
    private void markApplied(ActivityPollEntity p){p.setResultApplyStatus("APPLIED");p.setAppliedAt(LocalDateTime.now());p.setUpdateTime(LocalDateTime.now());p.setVersion(p.getVersion()+1);pollMapper.updateById(p);} private void review(ActivityPollEntity p){p.setResultApplyStatus("REVIEW_REQUIRED");p.setUpdateTime(LocalDateTime.now());p.setVersion(p.getVersion()+1);pollMapper.updateById(p);}
    private void applyPayload(ActivityItineraryEntity i,Map<String,Object> m){if(m.containsKey("title"))i.setTitle(str(m,"title"));if(m.containsKey("itineraryType"))i.setItineraryType(upperOr(str(m,"itineraryType"),i.getItineraryType()));if(m.containsKey("locationName"))i.setLocationName(str(m,"locationName"));if(m.containsKey("address"))i.setAddress(str(m,"address"));if(m.containsKey("description"))i.setDescription(str(m,"description"));if(m.containsKey("allDay"))i.setAllDay(bool(m,"allDay")?1:0);if(m.containsKey("startTime"))i.setStartTime(time(m,"startTime"));if(m.containsKey("endTime"))i.setEndTime(time(m,"endTime"));if(Integer.valueOf(1).equals(i.getAllDay())){i.setStartTime(null);i.setEndTime(null);}}
    private PollDetailResponse detailInternal(Long activityId,Long pollId,Long userId){ActivityPollEntity p=requirePoll(activityId,pollId);List<ActivityPollOptionEntity> opts=optionMapper.selectList(new LambdaQueryWrapper<ActivityPollOptionEntity>().eq(ActivityPollOptionEntity::getPollId,pollId).orderByAsc(ActivityPollOptionEntity::getSortNo));List<ActivityPollVoteEntity> votes=voteMapper.selectList(new LambdaQueryWrapper<ActivityPollVoteEntity>().eq(ActivityPollVoteEntity::getPollId,pollId));Map<Long,Long>counts=votes.stream().collect(Collectors.groupingBy(ActivityPollVoteEntity::getOptionId,Collectors.counting()));List<ActivityPollVoteEntity> currentVotes=votes.stream().filter(v->userId.equals(v.getUserId())).sorted(Comparator.comparing(ActivityPollVoteEntity::getUpdateTime, Comparator.nullsLast(Comparator.naturalOrder())).reversed()).toList();if("SINGLE".equals(p.getVoteType())&&currentVotes.size()>1){log.warn("single vote data inconsistent: pollId={}, userId={}, activeOptionIds={}",pollId,userId,currentVotes.stream().map(ActivityPollVoteEntity::getOptionId).toList());currentVotes=currentVotes.subList(0,1);}Set<Long>selected=currentVotes.stream().map(ActivityPollVoteEntity::getOptionId).collect(Collectors.toCollection(LinkedHashSet::new));String target=null;if(p.getTargetItineraryId()!=null){ActivityItineraryEntity i=itineraryMapper.selectById(p.getTargetItineraryId());target=i==null?null:i.getTitle();}return new PollDetailResponse(p.getId(),p.getActivityId(),p.getTitle(),p.getDescription(),p.getPurpose(),p.getDecisionType(),p.getVoteType(),Integer.valueOf(1).equals(p.getAllowModify()),p.getDeadline(),p.getStatus(),p.getResultApplyMode(),p.getResultApplyStatus(),p.getTargetItineraryId(),target,p.getGeneratedItineraryId(),p.getWinnerOptionId(),map(p.getItineraryTemplate()),p.getCreatedBy(),p.getClosedAt(),p.getAppliedAt(),votes.stream().map(ActivityPollVoteEntity::getUserId).distinct().count(),selected.stream().toList(),opts.stream().map(o->new PollOptionResponse(o.getId(),o.getOptionText(),o.getOptionDescription(),map(o.getResultPayload()),o.getSortNo(),counts.getOrDefault(o.getId(),0L),selected.contains(o.getId()))).toList());}
    private List<PollListItemResponse> listInternal(Long activityId,Long userId){List<ActivityPollEntity>polls=pollMapper.selectList(new LambdaQueryWrapper<ActivityPollEntity>().eq(ActivityPollEntity::getActivityId,activityId).orderByDesc(ActivityPollEntity::getCreateTime));return polls.stream().map(p->{List<ActivityPollVoteEntity>v=voteMapper.selectList(new LambdaQueryWrapper<ActivityPollVoteEntity>().eq(ActivityPollVoteEntity::getPollId,p.getId()));String target=null;if(p.getTargetItineraryId()!=null){ActivityItineraryEntity i=itineraryMapper.selectById(p.getTargetItineraryId());target=i==null?null:i.getTitle();}return new PollListItemResponse(p.getId(),p.getTitle(),p.getPurpose(),p.getDecisionType(),p.getVoteType(),p.getStatus(),p.getResultApplyStatus(),p.getTargetItineraryId(),p.getGeneratedItineraryId(),target,p.getDeadline(),v.stream().map(ActivityPollVoteEntity::getUserId).distinct().count(),v.stream().anyMatch(x->userId.equals(x.getUserId())),p.getWinnerOptionId());}).toList();}
    private ActivityPollEntity requirePoll(Long activityId,Long pollId){ActivityPollEntity p=pollMapper.selectById(pollId);if(p==null||!activityId.equals(p.getActivityId()))throw new NotFoundException("投票不存在");return p;}private ActivityPollOptionEntity requireOption(Long pollId,Long optionId){ActivityPollOptionEntity o=optionMapper.selectById(optionId);if(o==null||!pollId.equals(o.getPollId()))throw new NotFoundException("投票选项不存在");return o;}private ActivityItineraryEntity requireTarget(ActivityPollEntity p){ActivityItineraryEntity i=itineraryMapper.selectById(p.getTargetItineraryId());if(i==null||!p.getActivityId().equals(i.getActivityId()))throw param("关联行程不存在");return i;}
    private void requirePollManager(ActivityEntity a,ActivityMemberEntity m,Long userId,ActivityPollEntity p){if(!userId.equals(p.getCreatedBy())&&!access.isActivityCreator(a,m,userId))throw new ForbiddenException("只能管理自己创建的投票");}
    private String json(Map<String,Object>m){if(m==null||m.isEmpty())return null;try{return objectMapper.writeValueAsString(m);}catch(JsonProcessingException e){throw param("投票结果内容格式错误");}}private Map<String,Object> map(String json){if(!StringUtils.hasText(json))return new LinkedHashMap<>();try{return objectMapper.readValue(json,new TypeReference<LinkedHashMap<String,Object>>(){});}catch(JsonProcessingException e){throw new BusinessException("投票数据格式异常");}}
    private String str(Map<String,Object>m,String k){Object v=m.get(k);return v==null?null:String.valueOf(v).trim();}private boolean bool(Map<String,Object>m,String k){Object v=m.get(k);return v instanceof Boolean b?b:Boolean.parseBoolean(String.valueOf(v));}private LocalTime time(Map<String,Object>m,String k){String v=str(m,k);return StringUtils.hasText(v)?LocalTime.parse(v):null;}private String upper(String v){return v==null?null:v.trim().toUpperCase();}private String upperOr(String v,String d){return StringUtils.hasText(v)?upper(v):d;}private String trim(String v){return StringUtils.hasText(v)?v.trim():null;}private BusinessException param(String m){return new BusinessException(ErrorCode.PARAM_ERROR.code(),m);}
}
